PIPELINE_STAGES = [
    "INIT",
    "EVENTS_LOADED",
    "DATASET_EXTENDED_OR_VALIDATED",
    "SESSIONS_RECONSTRUCTED",
    "FUNNEL_AGGREGATED",
    "SEGMENTS_AGGREGATED",
    "HYPOTHESES_GENERATED",
    "LIFT_POTENTIAL_COMPUTED",
    "RANKINGS_CRITIQUED",
    "EXPERIMENTS_GENERATED",
    "SAMPLE_SIZES_COMPUTED",
    "REPORT_GENERATED",
    "OPTIONAL_CHECKS_COMPLETE",
    "VALIDATION_COMPLETE",
    "RESULTS_FINALISED"
]